---
    - name: Installer nfs utilities.
      package:
        name:
          - nfs-utils
          - libselinux-python
        state: present
    
    - name: Ensure directories to export exist
      file:
        path: "{{ item.mount }}"
        state: directory
        owner: root
        group: root
        mode: 0777
      with_items: "{{ nfs_exports }}"

    - name: Template exports file.
      template:
        src: exports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: 0644
      notify: reload nfs-server
    
    - name: "Ensure service {{item}} enabled and started"
      service:
        name: "{{item}}"
        state: started
        enabled: yes
      with_items:
        - rpcbind
        - nfs-server
        - nfs-lock
        - nfs-idmap
    