---
- name: Deploy EFK
  command: kubectl apply --kubeconfig={{ role_path }}/files/kubeconfig -f -
  args:
    stdin: "{{ item }}"
  with_items:
    - "{{ lookup('template', 'elasticsearch_persistence_volume.yml.j2') }}"
    - "{{ lookup('template', 'elasticsearch_persistence_volume_claims.yml.j2') }}"
    - "{{ lookup('template', 'elasticsearch_svc.yml.j2') }}"
    - "{{ lookup('template', 'elasticsearch_statefulset.yml.j2') }}"
    - "{{ lookup('template', 'kibana_service.yml.j2') }}"
    - "{{ lookup('template', 'kibana_deployment.yml.j2') }}"
    - "{{ lookup('template', 'fluentd_serviceaccount.yml.j2') }}"
    - "{{ lookup('template', 'fluentd_clusterrole.yml.j2') }}"
    - "{{ lookup('template', 'fluentd_clusterrolebinding.yml.j2') }}"
    - "{{ lookup('template', 'fluentd_daemonset.yml.j2') }}"
    - "{{ lookup('template', 'counter.yml.j2') }}"
    

