---
- name: Deploy EFK
  command: kubectl apply --kubeconfig={{ role_path }}/files/kubeconfig -f -
  args:
    stdin: "{{ item }}"
  with_items:
    - "{{ lookup('template', 'elasticsearch_svc.yml.j2') }}"
